FROM debian:bookworm-slim AS build
RUN apt-get update && apt-get install -y --no-install-recommends g++ make && rm -rf /var/lib/apt/lists/*
COPY . /src
WORKDIR /src
RUN make -j$(nproc)

FROM scratch
COPY --from=build /src/YSF2DMR /YSF2DMR
